Add possibility to define an application stack
equinor/terraform-azurerm-web-app pull request #160
Opened 2024-02-22 07:01 UTC by stiross79

Added the possibility to define an application stack to define a docker container to be used by the app.

### Checklist

- [ ] I've updated both the `azurerm_linux_web_app` and `azurerm_windows_web_app` resources.

2024-02-22 09:22 UTC, hknutsen requested changes
Implementation looks perfect 🎉 However, I've suggested an addition to the variable description to clarify any confusion around potential conflicts.

2024-02-22 09:22 UTC, hknutsen commented on variables.tf
> +  description = "A map of application stack settings for this Web App."
```suggestion
  description = "An object of application stack settings for this Web App. Note that application stack settings are often configured outside of Terraform (for example when deploying code), so configuring application stack settings in Terraform may cause conflicts."
```

2024-02-22 09:24 UTC, helenakallekleiv commented
I've also run the tests, and everything is looking nice 🎉

2024-02-22 13:37 UTC, hknutsen commented
Alternative solution: configure these values as app settings through #164

2024-02-26 14:16 UTC, hknutsen approved these changes
Looks good 👍

2024-02-26 14:20 UTC, helenakallekleiv approved these changes
Looking good 🌸

2024-02-26 14:22 UTC, merged